export const homeAmountCard = [
  {
    type: "top up",
    price: 220.78,
    at: 1,
  },
  {
    type: "sell",
    price: 230.78,
    at: 1,
  },
];

export const recentTransaction = [
  {
    id: 1,
    detail: "Wallet Top Up",
    time: "12:00pm",
    date: "12 Jan",
    transType: "send",
    amount: 16.55,
  },
  {
    id: 2,
    detail: "Money Sent",
    time: "12:00pm",
    date: "12 Jan",
    transType: "receive",
    amount: 16.55,
  },
  {
    id: 3,
    detail: "Withdrawn",
    time: "12:00pm",
    date: "12 Jan",
    transType: "receive",
    amount: 16.55,
  },
  {
    id: 4,
    detail: "Money Sent",
    time: "12:00pm",
    date: "12 Jan",
    transType: "send",
    amount: 16.55,
  },
  {
    id: 5,
    detail: "Money Sent",
    time: "12:00pm",
    date: "12 Jan",
    transType: "receive",
    amount: 16.55,
  },
  {
    id: 6,
    detail: "Wallet Top Up",
    time: "12:00pm",
    date: "12 Jan",
    transType: "send",
    amount: 16.55,
  },
  {
    id: 7,
    detail: "Bill Payment",
    time: "10:30am",
    date: "13 Jan",
    transType: "send",
    amount: 25.0,
  },
  {
    id: 8,
    detail: "Money Sent",
    time: "11:45am",
    date: "13 Jan",
    transType: "receive",
    amount: 50.75,
  },
  {
    id: 9,
    detail: "Wallet Top Up",
    time: "1:15pm",
    date: "14 Jan",
    transType: "send",
    amount: 30.0,
  },
  {
    id: 10,
    detail: "Withdrawn",
    time: "2:30pm",
    date: "14 Jan",
    transType: "receive",
    amount: 45.0,
  },
  {
    id: 11,
    detail: "Money Sent",
    time: "3:45pm",
    date: "15 Jan",
    transType: "send",
    amount: 60.0,
  },
  {
    id: 12,
    detail: "Wallet Top Up",
    time: "4:00pm",
    date: "15 Jan",
    transType: "send",
    amount: 10.0,
  },
  
];
